### ISSUE TITLE
[-]couldn't select target: TypeError: Cannot read property 'primary_target' of undefined

### ISSUE THREAD

**Issue by alecmoran1** [claissg/humble_chameleon#3]
Hi, 

not sure if I am not following the instruction correctly or not, but although the config.json file and the value of primary_target is set I am getting the following error:

[-]couldn't select target: TypeError: Cannot read property 'primary_target' of undefined

I would appreciate your help on this!

**Comment by fkasler** [comment]
This usually is happens when you put a subdomain instead of a domain in the options. The beginning of the config block should look like:

{
"phishing_domain.com": {
        "primary_target": "target1.com",
        "secondary_target": "target2.com",
        ...
}

The tool parses the subdomain to attack based on the requested URL. Therefore, DO NOT use subdomains like so:

{
"www.phishing_domain.com": {
        "primary_target": "target1.com",
        "secondary_target": "target2.com",
        ...
}

OR

{
"phishing_domain.com": {
        "primary_target": "www.target1.com",
        "secondary_target": "vpn.target2.com",
        ...
}

Please let me know if this was or was not your issue and we can look into it further. I will leave the thread open for now.

**Comment by fkasler** [comment]
I added a fallback_config to prevent this issue as well. Check out the new sample_config in the setup.
